//
// Account.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Account: Codable {

    public var _id: Int64?
    public var clientId: Int64?
    public var groupId: Int64?
    public var leverage: Int?
    public var stopOut: Int?
    public var minDeposit: Double?
    public var marginCall: Int?
    public var orderCount: Int?
    public var registrationDate: Date?
    public var lastLoginDate: Date?
    public var lastTradeDate: Date?
    public var allowTrade: Bool?
    public var disabled: Bool?
    public var lastLoginIp: String?
    public var balance: Double?
    public var credit: Double?
    public var margin: Double?
    public var marginFree: Double?
    public var marginLevel: Double?
    public var totalProfits: Double?
    public var equity: Double?
    public var balanceWithBonusesAndCredit: Double?
    public var bonus: Double?
    public var currency: String?
    public var isDemo: Bool?
    public var username: String?

    public init(_id: Int64? = nil, clientId: Int64? = nil, groupId: Int64? = nil, leverage: Int? = nil, stopOut: Int? = nil, minDeposit: Double? = nil, marginCall: Int? = nil, orderCount: Int? = nil, registrationDate: Date? = nil, lastLoginDate: Date? = nil, lastTradeDate: Date? = nil, allowTrade: Bool? = nil, disabled: Bool? = nil, lastLoginIp: String? = nil, balance: Double? = nil, credit: Double? = nil, margin: Double? = nil, marginFree: Double? = nil, marginLevel: Double? = nil, totalProfits: Double? = nil, equity: Double? = nil, balanceWithBonusesAndCredit: Double? = nil, bonus: Double? = nil, currency: String? = nil, isDemo: Bool? = nil, username: String? = nil) {
        self._id = _id
        self.clientId = clientId
        self.groupId = groupId
        self.leverage = leverage
        self.stopOut = stopOut
        self.minDeposit = minDeposit
        self.marginCall = marginCall
        self.orderCount = orderCount
        self.registrationDate = registrationDate
        self.lastLoginDate = lastLoginDate
        self.lastTradeDate = lastTradeDate
        self.allowTrade = allowTrade
        self.disabled = disabled
        self.lastLoginIp = lastLoginIp
        self.balance = balance
        self.credit = credit
        self.margin = margin
        self.marginFree = marginFree
        self.marginLevel = marginLevel
        self.totalProfits = totalProfits
        self.equity = equity
        self.balanceWithBonusesAndCredit = balanceWithBonusesAndCredit
        self.bonus = bonus
        self.currency = currency
        self.isDemo = isDemo
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case clientId
        case groupId
        case leverage
        case stopOut
        case minDeposit
        case marginCall
        case orderCount
        case registrationDate
        case lastLoginDate
        case lastTradeDate
        case allowTrade
        case disabled
        case lastLoginIp
        case balance
        case credit
        case margin
        case marginFree
        case marginLevel
        case totalProfits
        case equity
        case balanceWithBonusesAndCredit
        case bonus
        case currency
        case isDemo
        case username
    }

}
