//
// ApiUserModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApiUserModel: Codable {

    public var userName: String?
    public var enabled: Bool?
    public var createdDate: Date?
    public var iPs: [String]?
    public var idToken: String?
    public var signatureKey: String?
    public var _description: String?

    public init(userName: String? = nil, enabled: Bool? = nil, createdDate: Date? = nil, iPs: [String]? = nil, idToken: String? = nil, signatureKey: String? = nil, _description: String? = nil) {
        self.userName = userName
        self.enabled = enabled
        self.createdDate = createdDate
        self.iPs = iPs
        self.idToken = idToken
        self.signatureKey = signatureKey
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case userName
        case enabled
        case createdDate
        case iPs
        case idToken
        case signatureKey
        case _description = "description"
    }

}
