//
// Assembly.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Assembly: Codable {

    public var definedTypes: [TypeInfo]?
    public var exportedTypes: [ModelType]?
    public var codeBase: String?
    public var fullName: String?
    public var imageRuntimeVersion: String?
    public var isDynamic: Bool?
    public var location: String?
    public var reflectionOnly: Bool?
    public var isCollectible: Bool?
    public var isFullyTrusted: Bool?
    public var customAttributes: [CustomAttributeData]?
    public var escapedCodeBase: String?
    public var modules: [Module]?
    public var globalAssemblyCache: Bool?
    public var hostContext: Int64?

    public init(definedTypes: [TypeInfo]? = nil, exportedTypes: [ModelType]? = nil, codeBase: String? = nil, fullName: String? = nil, imageRuntimeVersion: String? = nil, isDynamic: Bool? = nil, location: String? = nil, reflectionOnly: Bool? = nil, isCollectible: Bool? = nil, isFullyTrusted: Bool? = nil, customAttributes: [CustomAttributeData]? = nil, escapedCodeBase: String? = nil, modules: [Module]? = nil, globalAssemblyCache: Bool? = nil, hostContext: Int64? = nil) {
        self.definedTypes = definedTypes
        self.exportedTypes = exportedTypes
        self.codeBase = codeBase
        self.fullName = fullName
        self.imageRuntimeVersion = imageRuntimeVersion
        self.isDynamic = isDynamic
        self.location = location
        self.reflectionOnly = reflectionOnly
        self.isCollectible = isCollectible
        self.isFullyTrusted = isFullyTrusted
        self.customAttributes = customAttributes
        self.escapedCodeBase = escapedCodeBase
        self.modules = modules
        self.globalAssemblyCache = globalAssemblyCache
        self.hostContext = hostContext
    }


}
