//
// AuthenticationViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthenticationViewModel: Codable {

    public var login: String
    public var password: String
    public var clientType: Int
    public var useLongTimeRefreshToken: Bool

    public init(login: String, password: String, clientType: Int, useLongTimeRefreshToken: Bool) {
        self.login = login
        self.password = password
        self.clientType = clientType
        self.useLongTimeRefreshToken = useLongTimeRefreshToken
    }
}
