//
// AuthenticationResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthenticationResult: Codable {

    public var token: String?
    public var refreshToken: String?
    public var client: Client?
    public var symbols: [Symbol]?
    public var symbolGroups: [SymbolGroup]?
    public var positions: [Position]?
    public var orders: [Order]?
    public var tradingHours: [TradingHours]?
    public var tradingHoursHolidays: [TradingHoursHolidays]?
    public var previousDayLatestQuotes: [Quote]?
    public var latestQuotes: [Quote]?

    public init(token: String? = nil, refreshToken: String? = nil, client: Client? = nil, symbols: [Symbol]? = nil, symbolGroups: [SymbolGroup]? = nil, positions: [Position]? = nil, orders: [Order]? = nil, tradingHours: [TradingHours]? = nil, tradingHoursHolidays: [TradingHoursHolidays]? = nil, previousDayLatestQuotes: [Quote]? = nil, latestQuotes: [Quote]? = nil) {
        self.token = token
        self.refreshToken = refreshToken
        self.client = client
        self.symbols = symbols
        self.symbolGroups = symbolGroups
        self.positions = positions
        self.orders = orders
        self.tradingHours = tradingHours
        self.tradingHoursHolidays = tradingHoursHolidays
        self.previousDayLatestQuotes = previousDayLatestQuotes
        self.latestQuotes = latestQuotes
    }


}
