//
// BecomeFollowerModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BecomeFollowerModel: Codable {

    public var accountId: Int64?

    public init(accountId: Int64? = nil) {
        self.accountId = accountId
    }


}
