//
// BecomeProTraderModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BecomeProTraderModel: Codable {

    public var accountId: Int64
    public var minimunInvestedAmount: Double
    public var username: String

    public init(accountId: Int64, minimunInvestedAmount: Double, username: String) {
        self.accountId = accountId
        self.minimunInvestedAmount = minimunInvestedAmount
        self.username = username
    }
}
