//
// ChartStorageInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChartStorageInfo: Codable {

    public var candlesCount: Int?
    public var rangeStart: Date?
    public var rangeEnd: Date?

    public init(candlesCount: Int? = nil, rangeStart: Date? = nil, rangeEnd: Date? = nil) {
        self.candlesCount = candlesCount
        self.rangeStart = rangeStart
        self.rangeEnd = rangeEnd
    }


}
