//
// ClosedTradeModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClosedTradeModel: Codable {

    public var symbol: String?
    public var profit: Double?
    public var volume: Double?
    public var closedTradesAmount: Int?
    public var percentInClosedTrades: Double?

    public init(symbol: String? = nil, profit: Double? = nil, volume: Double? = nil, closedTradesAmount: Int? = nil, percentInClosedTrades: Double? = nil) {
        self.symbol = symbol
        self.profit = profit
        self.volume = volume
        self.closedTradesAmount = closedTradesAmount
        self.percentInClosedTrades = percentInClosedTrades
    }


}
