//
// ConstructorInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ConstructorInfo: Codable {

    public var name: String?
    public var module: Module?
    public var customAttributes: [CustomAttributeData]?
    public var isCollectible: Bool?
    public var metadataToken: Int?
    public var isAbstract: Bool?
    public var isConstructor: Bool?
    public var isFinal: Bool?
    public var isHideBySig: Bool?
    public var isSpecialName: Bool?
    public var isStatic: Bool?
    public var isVirtual: Bool?
    public var isAssembly: Bool?
    public var isFamily: Bool?
    public var isFamilyAndAssembly: Bool?
    public var isFamilyOrAssembly: Bool?
    public var isPrivate: Bool?
    public var isPublic: Bool?
    public var isConstructedGenericMethod: Bool?
    public var isGenericMethod: Bool?
    public var isGenericMethodDefinition: Bool?
    public var containsGenericParameters: Bool?
    public var methodHandle: RuntimeMethodHandle?
    public var isSecurityCritical: Bool?
    public var isSecuritySafeCritical: Bool?
    public var isSecurityTransparent: Bool?

    public init(name: String? = nil, module: Module? = nil, customAttributes: [CustomAttributeData]? = nil, isCollectible: Bool? = nil, metadataToken: Int? = nil, isAbstract: Bool? = nil, isConstructor: Bool? = nil, isFinal: Bool? = nil, isHideBySig: Bool? = nil, isSpecialName: Bool? = nil, isStatic: Bool? = nil, isVirtual: Bool? = nil, isAssembly: Bool? = nil, isFamily: Bool? = nil, isFamilyAndAssembly: Bool? = nil, isFamilyOrAssembly: Bool? = nil, isPrivate: Bool? = nil, isPublic: Bool? = nil, isConstructedGenericMethod: Bool? = nil, isGenericMethod: Bool? = nil, isGenericMethodDefinition: Bool? = nil, containsGenericParameters: Bool? = nil, methodHandle: RuntimeMethodHandle? = nil, isSecurityCritical: Bool? = nil, isSecuritySafeCritical: Bool? = nil, isSecurityTransparent: Bool? = nil) {
        self.name = name
        self.module = module
        self.customAttributes = customAttributes
        self.isCollectible = isCollectible
        self.metadataToken = metadataToken
        self.isAbstract = isAbstract
        self.isConstructor = isConstructor
        self.isFinal = isFinal
        self.isHideBySig = isHideBySig
        self.isSpecialName = isSpecialName
        self.isStatic = isStatic
        self.isVirtual = isVirtual
        self.isAssembly = isAssembly
        self.isFamily = isFamily
        self.isFamilyAndAssembly = isFamilyAndAssembly
        self.isFamilyOrAssembly = isFamilyOrAssembly
        self.isPrivate = isPrivate
        self.isPublic = isPublic
        self.isConstructedGenericMethod = isConstructedGenericMethod
        self.isGenericMethod = isGenericMethod
        self.isGenericMethodDefinition = isGenericMethodDefinition
        self.containsGenericParameters = containsGenericParameters
        self.methodHandle = methodHandle
        self.isSecurityCritical = isSecurityCritical
        self.isSecuritySafeCritical = isSecuritySafeCritical
        self.isSecurityTransparent = isSecurityTransparent
    }
}
