//
// CreateApiUserModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateApiUserModel: Codable {

    public var userName: String
    public var enabled: Bool?
    public var iPs: [String]
    public var idToken: String
    public var signatureKey: String
    public var _description: String?

    public init(userName: String, enabled: Bool? = nil, iPs: [String], idToken: String, signatureKey: String, _description: String? = nil) {
        self.userName = userName
        self.enabled = enabled
        self.iPs = iPs
        self.idToken = idToken
        self.signatureKey = signatureKey
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case userName
        case enabled
        case iPs
        case idToken
        case signatureKey
        case _description = "description"
    }

}
