//
// CustomAttributeNamedArgument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomAttributeNamedArgument: Codable {

    public var memberInfo: MemberInfo?
    public var memberName: String?
    public var isField: Bool?

    public init(memberInfo: MemberInfo? = nil, memberName: String? = nil, isField: Bool? = nil) {
        self.memberInfo = memberInfo
        self.memberName = memberName
        self.isField = isField
    }


}
