//
// CustomAttributeData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomAttributeData: Codable {

    public var attributeType: ModelType?
    public var constructor: ConstructorInfo?
    public var namedArguments: [CustomAttributeNamedArgument]?

    public init(attributeType: ModelType? = nil, constructor: ConstructorInfo? = nil, namedArguments: [CustomAttributeNamedArgument]? = nil) {
        self.attributeType = attributeType
        self.constructor = constructor
        self.namedArguments = namedArguments
    }
}
