//
// Deal.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Deal: Codable {

    public var _id: Int64?
    public var externalId: String?
    public var accountId: Int64?
    public var orderId: Int64?
    public var isBuy: Bool?
    public var entry: Int?
    public var reason: Int?
    public var digits: Int?
    public var contractSize: Int?
    public var time: Date?
    public var symbol: String?
    public var symbolDisplayName: String?
    public var price: Double?
    public var profit: Double?
    public var swap: Double?
    public var margin: Double?
    public var commission: Double?
    public var rateProfit: Double?
    public var rateMargin: Double?
    public var comment: String?
    public var profitRaw: Double?
    public var pricePosition: Double?
    public var priceSL: Double?
    public var priceTP: Double?
    public var gateway: String?
    public var priceGateway: Double?
    public var volume: Double?
    public var volumeClosed: Double?
    public var tradeVolume: Double?
    public var marketBid: Double?
    public var marketAsk: Double?
    public var currentBalance: Double?
    public var createdIpAddress: String?
    public var positionId: Int64?
    public var timeUpdate: Date?
    public var timePosition: Date?
    public var operationId: String?
    public var bonusSpent: Double?
    public var positionIpAddress: String?

    public init(_id: Int64? = nil, externalId: String? = nil, accountId: Int64? = nil, orderId: Int64? = nil, isBuy: Bool? = nil, entry: Int? = nil, reason: Int? = nil, digits: Int? = nil, contractSize: Int? = nil, time: Date? = nil, symbol: String? = nil, symbolDisplayName: String? = nil, price: Double? = nil, profit: Double? = nil, swap: Double? = nil, margin: Double? = nil, commission: Double? = nil, rateProfit: Double? = nil, rateMargin: Double? = nil, comment: String? = nil, profitRaw: Double? = nil, pricePosition: Double? = nil, priceSL: Double? = nil, priceTP: Double? = nil, gateway: String? = nil, priceGateway: Double? = nil, volume: Double? = nil, volumeClosed: Double? = nil, tradeVolume: Double? = nil, marketBid: Double? = nil, marketAsk: Double? = nil, currentBalance: Double? = nil, createdIpAddress: String? = nil, positionId: Int64? = nil, timeUpdate: Date? = nil, timePosition: Date? = nil, operationId: String? = nil, bonusSpent: Double? = nil, positionIpAddress: String? = nil) {
        self._id = _id
        self.externalId = externalId
        self.accountId = accountId
        self.orderId = orderId
        self.isBuy = isBuy
        self.entry = entry
        self.reason = reason
        self.digits = digits
        self.contractSize = contractSize
        self.time = time
        self.symbol = symbol
        self.symbolDisplayName = symbolDisplayName
        self.price = price
        self.profit = profit
        self.swap = swap
        self.margin = margin
        self.commission = commission
        self.rateProfit = rateProfit
        self.rateMargin = rateMargin
        self.comment = comment
        self.profitRaw = profitRaw
        self.pricePosition = pricePosition
        self.priceSL = priceSL
        self.priceTP = priceTP
        self.gateway = gateway
        self.priceGateway = priceGateway
        self.volume = volume
        self.volumeClosed = volumeClosed
        self.tradeVolume = tradeVolume
        self.marketBid = marketBid
        self.marketAsk = marketAsk
        self.currentBalance = currentBalance
        self.createdIpAddress = createdIpAddress
        self.positionId = positionId
        self.timeUpdate = timeUpdate
        self.timePosition = timePosition
        self.operationId = operationId
        self.bonusSpent = bonusSpent
        self.positionIpAddress = positionIpAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case externalId
        case accountId
        case orderId
        case isBuy
        case entry
        case reason
        case digits
        case contractSize
        case time
        case symbol
        case symbolDisplayName
        case price
        case profit
        case swap
        case margin
        case commission
        case rateProfit
        case rateMargin
        case comment
        case profitRaw
        case pricePosition
        case priceSL
        case priceTP
        case gateway
        case priceGateway
        case volume
        case volumeClosed
        case tradeVolume
        case marketBid
        case marketAsk
        case currentBalance
        case createdIpAddress
        case positionId
        case timeUpdate
        case timePosition
        case operationId
        case bonusSpent
        case positionIpAddress
    }

}
