//
// EventInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EventInfo: Codable {

    public var name: String?
    public var declaringType: ModelType?
    public var reflectedType: ModelType?
    public var module: Module?
    public var customAttributes: [CustomAttributeData]?
    public var isCollectible: Bool?
    public var metadataToken: Int?

    public var isSpecialName: Bool?
    public var addMethod: MethodInfo?
    public var removeMethod: MethodInfo?
    public var raiseMethod: MethodInfo?
    public var isMulticast: Bool?
    public var eventHandlerType: ModelType?

    public init(name: String? = nil, declaringType: ModelType? = nil, reflectedType: ModelType? = nil, module: Module? = nil, customAttributes: [CustomAttributeData]? = nil, isCollectible: Bool? = nil, metadataToken: Int? = nil, isSpecialName: Bool? = nil, addMethod: MethodInfo? = nil, removeMethod: MethodInfo? = nil, raiseMethod: MethodInfo? = nil, isMulticast: Bool? = nil, eventHandlerType: ModelType? = nil) {
        self.name = name
        self.declaringType = declaringType
        self.reflectedType = reflectedType
        self.module = module
        self.customAttributes = customAttributes
        self.isCollectible = isCollectible
        self.metadataToken = metadataToken
        self.isSpecialName = isSpecialName
        self.addMethod = addMethod
        self.removeMethod = removeMethod
        self.raiseMethod = raiseMethod
        self.isMulticast = isMulticast
        self.eventHandlerType = eventHandlerType
    }


}
