//
// Exception.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Exception: Codable {
    public var message: String?
    public var helpLink: String?
    public var source: String?
    public var hResult: Int?
    public var stackTrace: String?

    public init(message: String? = nil, helpLink: String? = nil, source: String? = nil, hResult: Int? = nil, stackTrace: String? = nil) {
        self.message = message
        self.helpLink = helpLink
        self.source = source
        self.hResult = hResult
        self.stackTrace = stackTrace
    }
}
