//
// FavoriteSymbol.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FavoriteSymbol: Codable {

    public var _id: Int64?
    public var accountId: Int64?
    public var symbolName: String?

    public init(_id: Int64? = nil, accountId: Int64? = nil, symbolName: String? = nil) {
        self._id = _id
        self.accountId = accountId
        self.symbolName = symbolName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountId
        case symbolName
    }

}
