//
// FieldInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FieldInfo: Codable {

    public var name: String?
    public var declaringType: ModelType?
    public var reflectedType: ModelType?
    public var module: Module?
    public var customAttributes: [CustomAttributeData]?
    public var isCollectible: Bool?
    public var metadataToken: Int?
    public var fieldType: ModelType?
    public var isInitOnly: Bool?
    public var isLiteral: Bool?
    public var isNotSerialized: Bool?
    public var isPinvokeImpl: Bool?
    public var isSpecialName: Bool?
    public var isStatic: Bool?
    public var isAssembly: Bool?
    public var isFamily: Bool?
    public var isFamilyAndAssembly: Bool?
    public var isFamilyOrAssembly: Bool?
    public var isPrivate: Bool?
    public var isPublic: Bool?
    public var isSecurityCritical: Bool?
    public var isSecuritySafeCritical: Bool?
    public var isSecurityTransparent: Bool?
    public var fieldHandle: RuntimeFieldHandle?

    public init(name: String? = nil, declaringType: ModelType? = nil, reflectedType: ModelType? = nil, module: Module? = nil, customAttributes: [CustomAttributeData]? = nil, isCollectible: Bool? = nil, metadataToken: Int? = nil, fieldType: ModelType? = nil, isInitOnly: Bool? = nil, isLiteral: Bool? = nil, isNotSerialized: Bool? = nil, isPinvokeImpl: Bool? = nil, isSpecialName: Bool? = nil, isStatic: Bool? = nil, isAssembly: Bool? = nil, isFamily: Bool? = nil, isFamilyAndAssembly: Bool? = nil, isFamilyOrAssembly: Bool? = nil, isPrivate: Bool? = nil, isPublic: Bool? = nil, isSecurityCritical: Bool? = nil, isSecuritySafeCritical: Bool? = nil, isSecurityTransparent: Bool? = nil, fieldHandle: RuntimeFieldHandle? = nil) {
        self.name = name
        self.declaringType = declaringType
        self.reflectedType = reflectedType
        self.module = module
        self.customAttributes = customAttributes
        self.isCollectible = isCollectible
        self.metadataToken = metadataToken
        self.fieldType = fieldType
        self.isInitOnly = isInitOnly
        self.isLiteral = isLiteral
        self.isNotSerialized = isNotSerialized
        self.isPinvokeImpl = isPinvokeImpl
        self.isSpecialName = isSpecialName
        self.isStatic = isStatic
        self.isAssembly = isAssembly
        self.isFamily = isFamily
        self.isFamilyAndAssembly = isFamilyAndAssembly
        self.isFamilyOrAssembly = isFamilyOrAssembly
        self.isPrivate = isPrivate
        self.isPublic = isPublic
        self.isSecurityCritical = isSecurityCritical
        self.isSecuritySafeCritical = isSecuritySafeCritical
        self.isSecurityTransparent = isSecurityTransparent
        self.fieldHandle = fieldHandle
    }


}
