//
// HistoryServerOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HistoryServerOptions: Codable {

    public var host: String?
    public var groupId: String?
    public var isMain: Bool?

    public init(host: String? = nil, groupId: String? = nil, isMain: Bool? = nil) {
        self.host = host
        self.groupId = groupId
        self.isMain = isMain
    }


}
