//
// HistoryServerGroupOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct HistoryServerGroupOptions: Codable {

    public var key: String?
    public var historyServerOptions: [HistoryServerOptions]?

    public init(key: String? = nil, historyServerOptions: [HistoryServerOptions]? = nil) {
        self.key = key
        self.historyServerOptions = historyServerOptions
    }


}
