//
// Int64StringIEnumerableKeyValuePair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Int64StringIEnumerableKeyValuePair: Codable {

    public var key: Int64?
    public var value: [String]?

    public init(key: Int64? = nil, value: [String]? = nil) {
        self.key = key
        self.value = value
    }


}
