//
// MemberInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MemberInfo: Codable {

    public var name: String?
    public var declaringType: ModelType?
    public var reflectedType: ModelType?
    public var module: Module?
    public var customAttributes: [CustomAttributeData]?
    public var isCollectible: Bool?
    public var metadataToken: Int?

    public init(name: String? = nil, declaringType: ModelType? = nil, reflectedType: ModelType? = nil, module: Module? = nil, customAttributes: [CustomAttributeData]? = nil, isCollectible: Bool? = nil, metadataToken: Int? = nil) {
        self.name = name
        self.declaringType = declaringType
        self.reflectedType = reflectedType
        self.module = module
        self.customAttributes = customAttributes
        self.isCollectible = isCollectible
        self.metadataToken = metadataToken
    }


}
