//
// Module.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Module: Codable {

    public var assembly: Assembly?
    public var fullyQualifiedName: String?
    public var name: String?
    public var mdStreamVersion: Int?
    public var moduleVersionId: UUID?
    public var scopeName: String?
    public var moduleHandle: ModuleHandle?
    public var customAttributes: [CustomAttributeData]?
    public var metadataToken: Int?

    public init(assembly: Assembly? = nil, fullyQualifiedName: String? = nil, name: String? = nil, mdStreamVersion: Int? = nil, moduleVersionId: UUID? = nil, scopeName: String? = nil, moduleHandle: ModuleHandle? = nil, customAttributes: [CustomAttributeData]? = nil, metadataToken: Int? = nil) {
        self.assembly = assembly
        self.fullyQualifiedName = fullyQualifiedName
        self.name = name
        self.mdStreamVersion = mdStreamVersion
        self.moduleVersionId = moduleVersionId
        self.scopeName = scopeName
        self.moduleHandle = moduleHandle
        self.customAttributes = customAttributes
        self.metadataToken = metadataToken
    }


}
