//
// ModuleHandle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModuleHandle: Codable {

    public var mdStreamVersion: Int?

    public init(mdStreamVersion: Int? = nil) {
        self.mdStreamVersion = mdStreamVersion
    }


}
