//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Order: Codable {

    public var _id: Int64?
    public var externalId: Int64?
    public var accountId: Int64?
    public var symbol: String?
    public var digits: Int?
    public var contractSize: Int?
    public var state: Int?
    public var reason: Int?
    public var timeSetup: Date?
    public var timeExpiration: Date?
    public var timeDone: Date?
    public var type: Int?
    public var typeFill: Int?
    public var priceOrdered: Double?
    public var priceExecuted: Double?
    public var priceSL: Double?
    public var priceTP: Double?
    public var volumeInitialExt: Double?
    public var volumeCurrentExt: Double?
    public var positionId: Int64?
    public var rateMargin: Double?
    public var comment: String?
    public var volumeInitial: Double?
    public var volumeCurrent: Double?

    public init(_id: Int64? = nil, externalId: Int64? = nil, accountId: Int64? = nil, symbol: String? = nil, digits: Int? = nil, contractSize: Int? = nil, state: Int? = nil, reason: Int? = nil, timeSetup: Date? = nil, timeExpiration: Date? = nil, timeDone: Date? = nil, type: Int? = nil, typeFill: Int? = nil, priceOrdered: Double? = nil, priceExecuted: Double? = nil, priceSL: Double? = nil, priceTP: Double? = nil, volumeInitialExt: Double? = nil, volumeCurrentExt: Double? = nil, positionId: Int64? = nil, rateMargin: Double? = nil, comment: String? = nil, volumeInitial: Double? = nil, volumeCurrent: Double? = nil) {
        self._id = _id
        self.externalId = externalId
        self.accountId = accountId
        self.symbol = symbol
        self.digits = digits
        self.contractSize = contractSize
        self.state = state
        self.reason = reason
        self.timeSetup = timeSetup
        self.timeExpiration = timeExpiration
        self.timeDone = timeDone
        self.type = type
        self.typeFill = typeFill
        self.priceOrdered = priceOrdered
        self.priceExecuted = priceExecuted
        self.priceSL = priceSL
        self.priceTP = priceTP
        self.volumeInitialExt = volumeInitialExt
        self.volumeCurrentExt = volumeCurrentExt
        self.positionId = positionId
        self.rateMargin = rateMargin
        self.comment = comment
        self.volumeInitial = volumeInitial
        self.volumeCurrent = volumeCurrent
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case externalId
        case accountId
        case symbol
        case digits
        case contractSize
        case state
        case reason
        case timeSetup
        case timeExpiration
        case timeDone
        case type
        case typeFill
        case priceOrdered
        case priceExecuted
        case priceSL
        case priceTP
        case volumeInitialExt
        case volumeCurrentExt
        case positionId
        case rateMargin
        case comment
        case volumeInitial
        case volumeCurrent
    }

}
