//
// PositionCloseModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PositionCloseModel: Codable {

    public var accountId: Int64
    public var positionId: Int64
    public var volumePartial: Double

    public init(accountId: Int64, positionId: Int64, volumePartial: Double) {
        self.accountId = accountId
        self.positionId = positionId
        self.volumePartial = volumePartial
    }


}
