//
// ProTrader.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProTrader: Codable {
    public var _id: Int64?
    public var accountId: Int64?
    public var activeFrom: Date?
    public var commissionValue: Int?
    public var commissionsAmount: Double?
    public var minimumInvestedAmount: Double?
    public var subscribersCount: Int?
    public var gain: Double?
    public var averageProfit: Double?
    public var investedCapital: Double?
    public var popularity: Int?

    public init(_id: Int64? = nil, accountId: Int64? = nil, activeFrom: Date? = nil, commissionValue: Int? = nil, commissionsAmount: Double? = nil, minimumInvestedAmount: Double? = nil, subscribersCount: Int? = nil, gain: Double? = nil, averageProfit: Double? = nil, investedCapital: Double? = nil, popularity: Int? = nil) {
        self._id = _id
        self.accountId = accountId
        self.activeFrom = activeFrom
        self.commissionValue = commissionValue
        self.commissionsAmount = commissionsAmount
        self.minimumInvestedAmount = minimumInvestedAmount
        self.subscribersCount = subscribersCount
        self.gain = gain
        self.averageProfit = averageProfit
        self.investedCapital = investedCapital
        self.popularity = popularity
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountId
        case activeFrom
        case commissionValue
        case commissionsAmount
        case minimumInvestedAmount
        case subscribersCount
        case gain
        case averageProfit
        case investedCapital
        case popularity
    }

}
