//
// Quote.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct Quote: Codable, Identifiable, Hashable {
   
    public var id: String?  // Assuming id is a String
    public var symbol: String?
    public var date: String?
    public var ask: Double?
    public var bid: Double?
    
    public init(id: String? = nil, symbol: String? = nil, date: String? = nil, ask: Double? = nil, bid: Double? = nil) {
        self.id = id
        self.symbol = symbol
        self.date = date
        self.ask = ask
        self.bid = bid
    }
    
    // Custom initializer for decoding
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        // Decode other properties
        symbol = try container.decode(String.self, forKey: .symbol)
        date = try container.decode(String.self, forKey: .date)
        ask = try container.decode(Double.self, forKey: .ask)
        bid = try container.decode(Double.self, forKey: .bid)
        
        // Use the decoded "symbol" value as the id
        id = symbol
    }
}
