//
// QuoteViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QuoteViewModel: Codable {

    public var symbol: String?
    public var date: Date?
    public var ask: Double?
    public var bid: Double?

    public init(symbol: String? = nil, date: Date? = nil, ask: Double? = nil, bid: Double? = nil) {
        self.symbol = symbol
        self.date = date
        self.ask = ask
        self.bid = bid
    }


}
