//
// RefreshTokenViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RefreshTokenViewModel: Codable {

    public var token: String
    public var refreshToken: String
    public var useLongTimeRefreshToken: Bool

    public init(token: String, refreshToken: String, useLongTimeRefreshToken: Bool) {
        self.token = token
        self.refreshToken = refreshToken
        self.useLongTimeRefreshToken = useLongTimeRefreshToken
    }


}
