//
// RuntimeTypeHandle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RuntimeTypeHandle: Codable {

    public var value: IntPtr?

    public init(value: IntPtr? = nil) {
        self.value = value
    }


}
