//
// SocialTradingSubscribeApiRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SocialTradingSubscribeApiRequest: Codable {

    public var subscriberAccountId: Int64
    public var proAccountUsername: String
    public var invested: Double
    public var stopLevel: Int
    public var copyPercentage: Int

    public init(subscriberAccountId: Int64, proAccountUsername: String, invested: Double, stopLevel: Int, copyPercentage: Int) {
        self.subscriberAccountId = subscriberAccountId
        self.proAccountUsername = proAccountUsername
        self.invested = invested
        self.stopLevel = stopLevel
        self.copyPercentage = copyPercentage
    }


}
