//
// SocialTradingSearchModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SocialTradingSearchModel: Codable {

    public var _id: Int64?
    public var username: String?
    public var picture: String?
    public var country: String?
    public var gain: Double?
    public var tradesAmount: Int?
    public var riskLevel: Double?
    public var investedCapital: Double?
    public var followersAmount: Int?
    public var image: String?

    public init(_id: Int64? = nil, username: String? = nil, picture: String? = nil, country: String? = nil, gain: Double? = nil, tradesAmount: Int? = nil, riskLevel: Double? = nil, investedCapital: Double? = nil, followersAmount: Int? = nil, image: String? = nil) {
        self._id = _id
        self.username = username
        self.picture = picture
        self.country = country
        self.gain = gain
        self.tradesAmount = tradesAmount
        self.riskLevel = riskLevel
        self.investedCapital = investedCapital
        self.followersAmount = followersAmount
        self.image = image
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case picture
        case country
        case gain
        case tradesAmount
        case riskLevel
        case investedCapital
        case followersAmount
        case image
    }

}
