//
// SocialTradingSearchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SocialTradingSearchRequest: Codable {

    public var country: String?
    public var symbolGroups: [String]?
    public var minGain: Double?
    public var riskLevelMin: Double?
    public var riskLevelMax: Double?
    public var averageProfitMin: Double?
    public var averageProfitMax: Double?

    public init(country: String? = nil, symbolGroups: [String]? = nil, minGain: Double? = nil, riskLevelMin: Double? = nil, riskLevelMax: Double? = nil, averageProfitMin: Double? = nil, averageProfitMax: Double? = nil) {
        self.country = country
        self.symbolGroups = symbolGroups
        self.minGain = minGain
        self.riskLevelMin = riskLevelMin
        self.riskLevelMax = riskLevelMax
        self.averageProfitMin = averageProfitMin
        self.averageProfitMax = averageProfitMax
    }


}
