//
// StringInt64StringIEnumerableKeyValuePairIEnumerableKeyValuePair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StringInt64StringIEnumerableKeyValuePairIEnumerableKeyValuePair: Codable {

    public var key: String?
    public var value: [Int64StringIEnumerableKeyValuePair]?

    public init(key: String? = nil, value: [Int64StringIEnumerableKeyValuePair]? = nil) {
        self.key = key
        self.value = value
    }


}
