//
// SwitchLogginedAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SwitchLogginedAccount: Codable {

    public var accountId: Int64
    public var token: String
    public var refreshToken: String
    public var useLongTimeRefreshToken: Bool

    public init(accountId: Int64, token: String, refreshToken: String, useLongTimeRefreshToken: Bool) {
        self.accountId = accountId
        self.token = token
        self.refreshToken = refreshToken
        self.useLongTimeRefreshToken = useLongTimeRefreshToken
    }


}
