//
// SymbolGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SymbolGroup: Codable, Hashable, Equatable {
        public var _id: Int64?
       public var name: String
       public var order: Int?

       public init(_id: Int64? = nil, name: String, order: Int? = nil) {
           self._id = _id
           self.name = name
           self.order = order
       }

       public enum CodingKeys: String, CodingKey {
           case _id = "id"
           case name
           case order
       }

       public func hash(into hasher: inout Hasher) {
           hasher.combine(_id)
           hasher.combine(name)
           hasher.combine(order)
       }
}
