//
// TokenApiModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenApiModel: Codable {

    public var token: String?
    public var refreshToken: String?

    public init(token: String? = nil, refreshToken: String? = nil) {
        self.token = token
        self.refreshToken = refreshToken
    }


}
