//
// TradingHoursHolidays.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TradingHoursHolidays: Codable {

    public var _id: Int64?
    public var enabled: Bool?
    public var _description: String?
    public var date: Date?
    public var intervals: IntervalsInfo?
    public var symbols: [String]?
    public var everyYear: Bool?

    public init(_id: Int64? = nil, enabled: Bool? = nil, _description: String? = nil, date: Date? = nil, intervals: IntervalsInfo? = nil, symbols: [String]? = nil, everyYear: Bool? = nil) {
        self._id = _id
        self.enabled = enabled
        self._description = _description
        self.date = date
        self.intervals = intervals
        self.symbols = symbols
        self.everyYear = everyYear
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case enabled
        case _description = "description"
        case date
        case intervals
        case symbols
        case everyYear
    }

}
