//
// UpdateApiUserModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateApiUserModel: Codable {

    public var userName: String
    public var enabled: Bool?
    public var iPs: [String]
    public var _description: String?

    public init(userName: String, enabled: Bool? = nil, iPs: [String], _description: String? = nil) {
        self.userName = userName
        self.enabled = enabled
        self.iPs = iPs
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case userName
        case enabled
        case iPs
        case _description = "description"
    }

}
