//
// UpdateHistoryServerOptionsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateHistoryServerOptionsModel: Codable {

    public var historyServerOptions: [HistoryServerOptionsModel]?

    public init(historyServerOptions: [HistoryServerOptionsModel]? = nil) {
        self.historyServerOptions = historyServerOptions
    }


}
